# Generated by Django 2.2.16 on 2022-09-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220918_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'ordering': ['title', 'genre']},
        ),
    ]
